name: "Chromatic"

on:
    push:
        branches:
            - develop
    pull_request:

jobs:
    chromatic:
        name: Run Chromatic
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Enable Corepack
              run: corepack enable
            - name: Set Yarn version to 4.3.1
              run: corepack prepare yarn@4.3.1 --activate
            - name: Install dependencies
              run: yarn install
            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
